VEHICLES = [
    {
        "id": 1,
        "type": "4W",
        "brand": "BMW",
        "model": "iX1 LWB",
        "price_lakh": 49.0,
        "fuel": "ev",
        "transmission": "Automatic",
        "range_km": 531,
        "seating": 5,
        "usage": ["luxury", "family", "urban"],
        "highlights": ["Panoramic roof", "Connected cockpit", "Fast charging"],
    },
    {
        "id": 2,
        "type": "4W",
        "brand": "Mercedes-Benz",
        "model": "GLA 220d",
        "price_lakh": 58.0,
        "fuel": "diesel",
        "transmission": "Automatic",
        "range_km": 18,
        "seating": 5,
        "usage": ["luxury", "family", "touring"],
        "highlights": ["Premium cabin", "Highway comfort", "Strong diesel torque"],
    },
    {
        "id": 3,
        "type": "4W",
        "brand": "Toyota",
        "model": "Camry Hybrid",
        "price_lakh": 48.0,
        "fuel": "hybrid",
        "transmission": "e-CVT",
        "range_km": 25,
        "seating": 5,
        "usage": ["family", "touring", "luxury"],
        "highlights": ["Rear seat comfort", "Efficient hybrid drive", "Quiet cabin"],
    },
    {
        "id": 4,
        "type": "4W",
        "brand": "Mahindra",
        "model": "XEV 9e",
        "price_lakh": 31.5,
        "fuel": "ev",
        "transmission": "Automatic",
        "range_km": 656,
        "seating": 5,
        "usage": ["urban", "family", "luxury"],
        "highlights": ["Long EV range", "Futuristic dashboard", "ADAS features"],
    },
    {
        "id": 5,
        "type": "4W",
        "brand": "Tata",
        "model": "Harrier EV",
        "price_lakh": 28.0,
        "fuel": "ev",
        "transmission": "Automatic",
        "range_km": 500,
        "seating": 5,
        "usage": ["family", "adventure", "urban"],
        "highlights": ["Bold SUV stance", "Spacious cabin", "New-age infotainment"],
    },
    {
        "id": 6,
        "type": "4W",
        "brand": "Škoda",
        "model": "Kodiaq",
        "price_lakh": 46.0,
        "fuel": "petrol",
        "transmission": "DSG Automatic",
        "range_km": 14,
        "seating": 7,
        "usage": ["family", "touring", "luxury"],
        "highlights": ["7-seat versatility", "Premium interior", "Strong road presence"],
    },
    {
        "id": 7,
        "type": "4W",
        "brand": "Kia",
        "model": "EV6",
        "price_lakh": 61.0,
        "fuel": "ev",
        "transmission": "Automatic",
        "range_km": 708,
        "seating": 5,
        "usage": ["luxury", "sport", "touring"],
        "highlights": ["Ultra-fast charging", "Performance styling", "Premium digital cockpit"],
    },
    {
        "id": 8,
        "type": "2W",
        "brand": "Ather",
        "model": "450 Apex",
        "price_lakh": 1.95,
        "fuel": "ev",
        "transmission": "Automatic",
        "range_km": 157,
        "seating": 2,
        "usage": ["urban", "sport"],
        "highlights": ["Sharp acceleration", "Smart dashboard", "Fast urban charging"],
    },
    {
        "id": 9,
        "type": "2W",
        "brand": "Ultraviolette",
        "model": "F77 Mach 2",
        "price_lakh": 3.99,
        "fuel": "ev",
        "transmission": "Automatic",
        "range_km": 323,
        "seating": 2,
        "usage": ["sport", "touring"],
        "highlights": ["Aggressive design", "Track-inspired performance", "Large battery pack"],
    },
    {
        "id": 10,
        "type": "2W",
        "brand": "TVS",
        "model": "iQube ST",
        "price_lakh": 1.55,
        "fuel": "ev",
        "transmission": "Automatic",
        "range_km": 145,
        "seating": 2,
        "usage": ["urban", "family"],
        "highlights": ["Practical scooter design", "Connected features", "Easy city usability"],
    },
    {
        "id": 11,
        "type": "2W",
        "brand": "Royal Enfield",
        "model": "Himalayan 450",
        "price_lakh": 2.85,
        "fuel": "petrol",
        "transmission": "Manual",
        "range_km": 30,
        "seating": 2,
        "usage": ["adventure", "touring"],
        "highlights": ["Touring comfort", "Adventure chassis", "High ground clearance"],
    },
    {
        "id": 12,
        "type": "2W",
        "brand": "KTM",
        "model": "390 Duke",
        "price_lakh": 3.13,
        "fuel": "petrol",
        "transmission": "Manual",
        "range_km": 28,
        "seating": 2,
        "usage": ["sport", "urban"],
        "highlights": ["Streetfighter styling", "Quick handling", "Strong mid-range power"],
    },
]
